export const POST_ADD_TO_CART_PENDING = "POST_ADD_TO_CART_PENDING";
export const POST_ADD_TO_CART_SUCCESS = "POST_ADD_TO_CART_SUCCESS";
export const POST_ADD_TO_CART_ERROR = "POST_ADD_TO_CART_ERROR";
export const POST_ADD_TO_CART_INITIAL = "POST_ADD_TO_CART_INITIAL";
