export const POST_AUTH_PENDING = "POST_AUTH_PENDING";
export const POST_AUTH_SUCCESS = "POST_AUTH_SUCCESS";
export const POST_AUTH_ERROR = "POST_AUTH_ERROR";
export const POST_AUTH_INITIAL = "POST_AUTH_INITIAL";