export const DELETE_FROM_CART_PENDING = "DELETE_FROM_CART_PENDING";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_ERROR = "DELETE_FROM_CART_ERROR";
export const DELETE_FROM_CART_INITIAL = "DELETE_FROM_CART_INITIAL";
