export const GET_AUTH_PENDING = "GET_AUTH_PENDING";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
export const GET_AUTH_ERROR = "GET_AUTH_ERROR";
export const GET_AUTH_INITIAL = "GET_AUTH_INITIAL";
