export const GET_TSHIRT_DETAIL_PENDING = "GET_TSHIRT_DETAIL_PENDING";
export const GET_TSHIRT_DETAIL_SUCCESS = "GET_TSHIRT_DETAIL_SUCCESS";
export const GET_TSHIRT_DETAIL_ERROR = "GET_TSHIRT_DETAIL_ERROR";
